[package]
name = "kaiseki"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "kaiseki-core",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaiseki-core = { path = "kaiseki-core" }
tokio = { version = "1", features = ["full"] }
