[package]
name = "kaiseki-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
thiserror = "1"
tokio = { version = "1", optional = true, features = ["macros", "rt", "sync"] }
tracing = "0.1"

[features]
tokio = ["dep:tokio"]
