[package]
name = "kaiseki-gameboy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
bytes = { version = "1" }
futures = { version = "0.3" }
kaiseki-core = { path = "../kaiseki-core" }
tracing = { version = "0.1" }
