[package]
name = "kaiseki-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["fold", "full"] }
tokio = "1.0"
tracing = "0.1"
