[package]
name = "kaiseki-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1" }
crossbeam-channel = { version = "0.5" }
spin_sleep = { version = "1" }
tracing = { version = "0.1" }
uuid = { version = "1", features = ["v4"] }
