name: Test
on: [push, pull_request]

jobs:
  test:
    name: Lint, Audit, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy
      - name: Audit
        run: cargo audit
      - name: Test
        run: cargo test --all-features
